### ISSUE TITLE
一个内容之外的问题

### ISSUE THREAD

**Issue by Orisland** [mzdluo123/SurfingTutorial#4]
有没有一种可能，如果接触计算机较少，那么他可能一开始不会知道github这个平台，即使知道，github在国内的裸连速度堪忧，图片几乎完全无法加载。
如何让这个有用的项目让更多需要的人看到也许是很头疼的问题。

**Comment by mzdluo123** [comment]
现在这里使用markdown编写好之后可以方便的发到国内平台上

当然如果能有大家帮忙宣传更好
